# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 37e451070748fa2c550eba2ab5f970dfa34fd65eef84bd5d17562268e5c3fd171b4ec3802c398af65205bbbeb0c10853a86aa93712a21b7947b6805290e27f9d

test:
  secret_key_base: 8d2135896b4d23e686424e082b903176c2fff0fd1b8976232dca99862df51689de7c6f56d1615216d2af8151b822472f03184c9813eba0186ac140dadbd89e42

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
